services:
  - type: web
    plan: free
    name: event-ui
    runtime: node
    buildCommand: "pnpm install && pnpm run build"
    startCommand: "pnpm run preview --host 0.0.0.0"
    envVars:
      - key: VITE_API_URL
        value: "https://techtalks-api.onrender.com"
