services:
  - type: web
    plan: free
    name: event-ui
    runtime: node
    buildCommand: pnpm install && pnpm run type-check && pnpm run build
    startCommand: pnpm run preview --host 0.0.0.0 --port 10000
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: techtalks-api
          envVarKey: RENDER_EXTERNAL_URL
